### ISSUE TITLE
Espeak leaves Zombie processes after conversion

### ISSUE THREAD

**Issue by akshay-vishnoi** [dejan/espeak-ruby#10]
I am using this code in rails application and when I try following:

``` ruby
Speech.new(char).bytes.force_encoding('ASCII-8BIT')
```

It creates a process with name `espeak` in the system but doesn't kill it. Hence, as many times, it is called it leaves a zombie process behind, which are deleted only when we restart the application server. This has led to the memory leak. The change got added in the last version i.e. 1.0.3 due to `popen`. Any thoughts?

**Comment by dejan** [comment]
@akshay-vishnoi thanks for reporting and I'm sorry for delayed response. Fixed in #11
